### ISSUE TITLE
calculator freezes/slows down

### ISSUE THREAD

**Issue by auzwu** [KermMartian/ArTICL#11]
first, thanks for sharing this awsome project with the community..

i tried to connect my ti 84+ to an arduino uno but the calc freezes/slows down when connecting the white line (to pin2) and ground.. any idea what i'm doing wrong?

many thanks in advance

**Comment by KermMartian** [comment]
Hmm, that indicates that pin(s) are grounded, and the calculator is trying to communicate with a nonexistent endpoint. Some troubleshooting ideas:
(1) Make sure the link cable is going all the way into the link port and that there are no obstructions.
(2) Make sure the digital pins you're using are the ones that are specified in the ArTICL sketch.
(3) Make sure you've loaded an ArTICL sketch.

**Comment by KermMartian** [comment]
Closing this as hopefully solved after nearly three years.
