### ISSUE TITLE
'onSendAsCBL2' was not declared

### ISSUE THREAD

**Issue by MrApplecraft** [KermMartian/ArTICL#12]
When trying to compile every example the compiler throws 
error: 'onSendAsCBL2' was not declared in this scope
            onGetAsCBL2, onSendAsCBL2);
             ^
at me.

**Comment by KermMartian** [comment]
How have you installed the ArTICL library in your Arduino install? Did you put the unzipped ArTICL folder in (for example) My Documents\Arduino\libraries\?

**Comment by MrApplecraft** [comment]
Yep, everything in the library folder.
Btw. i´m running Ubuntu 14.04 with Arduino 1.6.8

**Comment by MrApplecraft** [comment]
Bump

**Comment by KermMartian** [comment]
I believe this issue has been repaired; I'm not sure why it didn't show up sooner. Apologies for the delay, and feel free to re-open if the issue recurs.
