### ISSUE TITLE
Is it possible to send a program using TICL

### ISSUE THREAD

**Issue by nullsemicolon** [KermMartian/ArTICL#24]
So I've been playing around with this wonderful library.  I found that using just the TICL portion of the library, I can have my ti-86 send me the bytes(name of program and basic code) for a program it has stored locally without a problem.  However, when I take those same bytes that it sent me and send them back to the TI-86 in receiving mode, I cannot get the TI-86 to acknowledge the transmission.  However, I am able to send keystroke, acknowledge, and continue commands just fine but they don't have a data portion to their packets.   Am I doing something wrong? Is it possible to send programs to the calculator using the TICL::Send command?  Either way,  awesome work on this.

**Comment by nullsemicolon** [comment]
Never mind figured it out

**Comment by KermMartian** [comment]
@nullsemicolon can you please share what you ended up writing for posterity/other folks looking to answer the same question?

**Comment by nullsemicolon** [comment]
Basically my problem was that I was accidently sending a bunch of null characters(/x00) at the end of the data instead of the exact data. The mistake was from being new to Arduino/C arrays.  I'm more than willing to share my code but the arduino is really just a middle man forwarding packets between my computers serial connection and the TI-86 cable. The guts of how the protocol communicates to send a file is all in python at the moment.

**Comment by KermMartian** [comment]
Thanks for clarifying, and good luck with the project! If you think it's something the rest of the calculator community would enjoy, please post it in the Your Projects subforum on Cemetech: https://www.cemetech.net/forum/viewforum.php?f=4
